SELECT * FROM TALUNO;

SELECT Concat(COD_ALUNO, NOME) FROM TALUNO;         --       CONCATENA

SELECT COD_ALUNO ||' -  ' || NOME FROM TALUNO;    --       CONCATENA

SELECT nome, InitCap(NOME) FROM TALUNO;         --  PRIMEIRA LETRA MAIUSCULA

SELECT nome, InStr(nome, 'R') FROM TALUNO;    --CONTAGEM DE R

SELECT nome, Length(NOME) FROM TALUNO;          --QTDE DE LETRAS

SELECT nome, Lower(NOME) FROM TALUNO;          --DEIXA TUDO MINUSCULO

SELECT nome, Upper(NOME) FROM TALUNO;          --   TUDO MAIUSCULO

SELECT InitCap('JOSE DA SILVA') FROM TALUNO; --  PRIMEIRA LETRA DE TODOS OS NOMES MAIUSCULO

SELECT nome, LPad(COD_ALUNO,5, '0') FROM TALUNO;          -- PREENCHE O CODIGO A ESQUERDA

SELECT nome, salario, RPad(SALARIO,8, '0') FROM TALUNO;        --   PREENCHE O CODIGO A DIREITA

SELECT nome, RPad(NOME,10, '$') FROM TALUNO;          -- PREENCHE O CODIGO A DIREITA

SELECT nome, SubStr(NOME, 1, 3) FROM TALUNO;             -- COPIA SÓ PARTE DE UM TEXTO, partir da posição 1 ele vai exibir as 3 proximas letras

SELECT nome, SubStr(NOME, 1, 1) FROM TALUNO;            -- COPIA SÓ PARTE DE UM TEXTO

SELECT nome, SubStr(NOME, 3, 1) FROM TALUNO;          -- COPIA SÓ PARTE DE UM TEXTO

SELECT REPLACE(NOME, 'R','$') FROM TALUNO;             --TROCA DE LETRAS

SELECT REPLACE(Lower(NOME), 'r','$') FROM TALUNO;      --TROCA DE LETRAS+DEIXAR EM LETRAS MINUSCULAS

SELECT nome, SubStr(NOME, Length(nome), 1) FROM TALUNO;     --PEGAR A ULTIMA LETRA

SELECT nome, SubStr(NOME, Length(nome) -1, 2) FROM TALUNO;          --CONTAR QUANTOS TEM -1 E PEGAR OS 2 ULTIMOS

SELECT nome, SubStr(NOME,3, Length(nome) -3) FROM TALUNO;

SELECT * FROM TALUNO
WHERE Lower(NOME) = 'jhow';

SELECT * FROM TALUNO
WHERE Upper(NOME) = 'JHOW';

SELECT * FROM TALUNO
WHERE Upper(SubStr(CIDADE, 1, 3)) = 'CAN';

UPDATE TALUNO SET
SALARIO = 633.47
WHERE COD_ALUNO = 1;

SELECT
SALARIO,
REPLACE(SALARIO, ',',''),
RPad(SALARIO, 10, '0'),    --Zeros a direita até 10 casas
LPad(SALARIO, 10, '0'),
LPad(REPLACE(SALARIO, '.',''),10,'0')
FROM TALUNO;

--DATA
SELECT * FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT Round(45.925, 2),  --45.93
       Trunc(45.929, 2),  --45.92
       Mod(10, 2) AS RESTO_DIVISAO,
       Trunc(1.99),
       Trunc(1.99, 2)
FROM DUAL;
               --DATAS
SELECT * FROM TCONTRATO;

SELECT DATA, SYSDATE, DATA + 5 FROM TCONTRATO;

SELECT SYSDATE - DATA AS DIF_DIAS FROM TCONTRATO;

SELECT Trunc(SYSDATE - DATA) AS DIAS FROM TCONTRATO;

SELECT SYSDATE, SYSDATE +2 / 24 AS ADD_HORAS FROM TCONTRATO;   -- SOMANDO HORAS EM DATA

SELECT SYSDATE, SYSDATE + 15 /1440 AS ASS_MINUTOS FROM TCONTRATO;   -- SOMANDO 15 MIN

SELECT SYSDATE, SYSDATE + 30 / (3600*24) AS ADD_SEGUNDOS FROM TCONTRATO; --ADICIONA 30 SEGUNDOS

SELECT SYSDATE, Trunc (SYSDATE) FROM DUAL--HORA FICA 00:00:00

SELECT Months_BETWEEN(SYSDATE, SYSDATE-90) AS DIF_MES FROM DUAL;

SELECT SYSDATE, Add_Months(SYSDATE, 5) AS ADICIONA_MES_DATA FROM DUAL;       --ADICIONA MESES

SELECT Next_Day(SYSDATE, 'QUARTA-FEIRA') AS PROXIMA_QUARTA_DATA FROM DUAL;

SELECT Last_Day(SYSDATE) AS ULTIMO_DIA_MES FROM DUAL;

SELECT Round(SYSDATE, 'MONTH') AS PRIMEIRO_DIA_PROXIMO_MES FROM DUAL;

SELECT Trunc(SYSDATE,'MONTH') AS PRIMEIRO_DIA_MES_CORRENTE FROM DUAL;

SELECT SYSDATE, To_Char(SYSDATE, 'DD') FROM DUAL;

SELECT To_Char(SYSDATE, 'DD/MM/YYYY') DATA FROM DUAL;

SELECT To_Char(SYSDATE, 'DD/MM') DIA_MES FROM DUAL;

SELECT To_Char(SYSDATE, 'MM') MES FROM DUAL;

SELECT To_Char(SYSDATE, 'YYYY') ANO FROM DUAL;

SELECT To_Char(SYSDATE, 'MONTH') MES1 FROM DUAL;

SELECT To_Char(SYSDATE, 'DY') DIA_SEMANA FROM DUAL;

SELECT To_Char(SYSDATE, 'D') MES FROM DUAL;

SELECT To_Char(SYSDATE, 'DAY') MES FROM DUAL;

SELECT To_Char(SYSDATE, 'YEAR') MES FROM DUAL;

SELECT To_Char(SYSDATE, ' "NOVO HAMBURGO", fmDAY "," DD "de" fmMonth "de" YYYY') MES FROM DUAL;

SELECT To_Char(SYSDATE, 'HH24:MI') HORA_MIN FROM DUAL;

SELECT To_Char(SYSDATE, 'HH24:MI:SS') HORA_MIN FROM DUAL;

SELECT To_Char(SYSDATE, 'DD/MM/YYYY HH24:MI') HORA_MIN FROM DUAL;




--L -> R$
--GG ->ponto
-- D -> casas decimais

SELECT * FROM TALUNO;
SELECT Trim(To_Char(Salario, 'L99999.99')) salario1, Trim(To_Char(Salario, 'L99G999D99')) salario2 FROM TALUNO;

SELECT 'R$ ' || (Round(Salario, 2)) AS salario FROM TALUNO;


SELECT Total,
       Desconto,
       Desconto+Total,
       Nvl(Desconto,0),
       Nvl(Desconto,0)+ TOTAL,
       Nvl2(Desconto, TOTAL, -1)
FROM TContrato;

SELECT * FROM TALUNO
ORDER BY COD_ALUNO;


UPDATE TALUNO
SET NOME = NULL
WHERE COD_ALUNO = 5;

SELECT Cod_Aluno, Nvl(Nome, 'SEM NOME') FROM TALUNO

UPDATE TALUNO SET
Estado = 'SC'
WHERE Cod_Aluno=3;

UPDATE TALUNO SET
Estado = 'RJ'
WHERE Cod_Aluno=5;

SELECT NOME, Estado,
        CASE
        WHEN Estado = 'RS' THEN 'GAUCHO'
        WHEN Estado = 'AC' THEN 'ACREANO'
        WHEN ESTADO = 'RJ' AND SALARIO>500 THEN 'CARIOCA'
        ELSE 'OUTROS'
        END AS Apelido
FROM TALUNO;

SELECT SYSDATE AS DATA FROM DUAL

SELECT NOME, ESTADO,
       Decode(ESTADO, 'RS','GAUCHO','AC', 'ACREANO','SP', 'PAULISTA', 'OUTROS') AS APELIDO
       FROM TALUNO;




