CREATE SEQUENCE SEQ_ALUNO1
START WITH 60
--VALOR INICIAL
INCREMENT BY 2
--QTDE A INCREMENTAR
MINVALUE 60
--VALOR MINIMO
MAXVALUE 100
--VALOR MAXIMO
NOCACHE
--NÃO GUARDA CACHE FAIXA DE VALORES
NOCYCLE;


INSERT INTO TALUNO (cod_aluno, NOME)
VALUES(Seq_Aluno1.NEXTVAL, 'MASTER TRAINING');

SELECT *
FROM TALUNO;


SELECT *
FROM USER_SEQUENCES;

SELECT SEQ_ALUNO1.CURRVAL FROM DUAL;

ALTER SEQUENCE SEQ_ALUNO1 MAXVALUE 500;

DROP SEQUENCE SEQ_ALUNO1;
CREATE SEQUENCE SEQ_ALUNO1 START WITH 80;
