CREATE TABLE TESTE
(
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    DAT DATE DEFAULT SYSDATE
);

SELECT *
FROM TESTE;

INSERT INTO TESTE(CODIGO)VALUES (1);

INSERT INTO TESTE(CODIGO,DATA)VALUES (2, '03/08/2013');
INSERT INTO TESTE(CODIGO,DATA)VALUES (2, '03/08/2013');

--TABELAS CRIADAS COM O MEU USUARIO
SELECT * FROM USER_TABLES;

--TABELAS CRIADAS DE TODOS OS USUARIOS
SELECT *
FROM ALL_TABLES;

--CRIAR A PARTIR DE UMA TABELA
CREATE TABLE TCONTRATO_VIP
AS SELECT *
FROM TCONTRATO WHERE TOTAL > 500;

SELECT * FROM TCONTRATO_VIP;

ALTER TABLE TCONTRATO_VIP ADD VALOR NUMBER(5,2);-- 999,99

ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(8,2);--

ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(12,2) DEFAULT 0;

ALTER TABLE TCONTRATO_VIP RENAME COLUMN VALOR TO VALOR2;

ALTER TABLE TCONTRATO_VIP DROP COLUMN VALOR2;

DROP TABLE TCONTRATO_VIP;

